In [1]:
from Hopfield import HopfieldModel, tune_model
from BnB import BnBMethod
from parseTSP import parsing
import numpy as np

### Сеть Хопфилда

In [2]:
matrix, answer = parsing('burma14', 0, 5)
A = [1000, 10000, 100000]
B = [1000, 10000, 100000]
C = [1000, 10000, 100000]
D= [50, 50, 50]
tune_model('burma14', matrix, 'sigmoid', A, B, C, D, 5)

In [3]:
matrix = np.array(parsing('burma14.xml', 0, 10))
print(matrix)
model = HopfieldModel(matrix, 'sigmoid',[100000, 100000, 100000, 50], 5)
model.start_network()
model.print_result()

[[   0.  153.  510.  706.  966.  581.  455.   70.  160.  372.]
 [ 153.    0.  422.  664.  997.  598.  507.  197.  311.  479.]
 [ 510.  422.    0.  289.  744.  390.  437.  491.  645.  880.]
 [ 706.  664.  289.    0.  491.  265.  410.  664.  804. 1070.]
 [ 966.  997.  744.  491.    0.  400.  514.  902.  990. 1261.]
 [ 581.  598.  390.  265.  400.    0.  168.  522.  634.  910.]
 [ 455.  507.  437.  410.  514.  168.    0.  389.  482.  757.]
 [  70.  197.  491.  664.  902.  522.  389.    0.  154.  406.]
 [ 160.  311.  645.  804.  990.  634.  482.  154.    0.  276.]
 [ 372.  479.  880. 1070. 1261.  910.  757.  406.  276.    0.]]
4264.0
[-2000000.0, -3800000.0, -5400000.0, -6600000.0, -7735500.0, -8647500.0, -9008500.0, -9108500.0, -9291400.0, -9491400.0, -9503400.0, -9509600.0, -9801100.0, -9926700.0, -10093100.0, -10125200.0, -10191500.0, -10291800.0, -10345700.0, -10372700.0, -10409000.0, -10428700.0, -10502600.0]
[0.4229915142059326, 0.36772894859313965, 0.36569976806640625, 0.36641740798

In [4]:
matrix = np.array(parsing('burma14.xml', 0, 11))
print(matrix)
model = HopfieldModel(matrix, 'sigmoid',[100000, 100000, 100000, 50], 5)
model.start_network()
model.print_result()

[[   0.  153.  510.  706.  966.  581.  455.   70.  160.  372.  157.]
 [ 153.    0.  422.  664.  997.  598.  507.  197.  311.  479.  310.]
 [ 510.  422.    0.  289.  744.  390.  437.  491.  645.  880.  618.]
 [ 706.  664.  289.    0.  491.  265.  410.  664.  804. 1070.  768.]
 [ 966.  997.  744.  491.    0.  400.  514.  902.  990. 1261.  947.]
 [ 581.  598.  390.  265.  400.    0.  168.  522.  634.  910.  593.]
 [ 455.  507.  437.  410.  514.  168.    0.  389.  482.  757.  439.]
 [  70.  197.  491.  664.  902.  522.  389.    0.  154.  406.  133.]
 [ 160.  311.  645.  804.  990.  634.  482.  154.    0.  276.   43.]
 [ 372.  479.  880. 1070. 1261.  910.  757.  406.  276.    0.  318.]
 [ 157.  310.  618.  768.  947.  593.  439.  133.   43.  318.    0.]]
4976.0
[-2200000.0, -4200000.0, -5800000.0, -7371100.0, -8522000.0, -9722000.0, -10506700.0, -11006700.0, -11161250.0, -11383100.0, -11554200.0, -11694400.0, -11767000.0, -11821300.0, -11901200.0, -11906200.0, -12018100.0, -12088000.0, -122

In [5]:
matrix = np.array(parsing('burma14.xml', 0, 12))
print(matrix)
model = HopfieldModel(matrix, 'sigmoid',[100000, 100000, 100000, 50], 5)
model.start_network()
model.print_result()

[[   0.  153.  510.  706.  966.  581.  455.   70.  160.  372.  157.  567.]
 [ 153.    0.  422.  664.  997.  598.  507.  197.  311.  479.  310.  581.]
 [ 510.  422.    0.  289.  744.  390.  437.  491.  645.  880.  618.  374.]
 [ 706.  664.  289.    0.  491.  265.  410.  664.  804. 1070.  768.  259.]
 [ 966.  997.  744.  491.    0.  400.  514.  902.  990. 1261.  947.  418.]
 [ 581.  598.  390.  265.  400.    0.  168.  522.  634.  910.  593.   19.]
 [ 455.  507.  437.  410.  514.  168.    0.  389.  482.  757.  439.  163.]
 [  70.  197.  491.  664.  902.  522.  389.    0.  154.  406.  133.  508.]
 [ 160.  311.  645.  804.  990.  634.  482.  154.    0.  276.   43.  623.]
 [ 372.  479.  880. 1070. 1261.  910.  757.  406.  276.    0.  318.  898.]
 [ 157.  310.  618.  768.  947.  593.  439.  133.   43.  318.    0.  582.]
 [ 567.  581.  374.  259.  418.   19.  163.  508.  623.  898.  582.    0.]]
6022.0
[-2400000.0, -4600000.0, -6600000.0, -8372400.0, -9882600.0, -11045400.0, -11982000.0, -1258

In [6]:
matrix = np.array(parsing('burma14.xml', 0, 13))
print(matrix)
model = HopfieldModel(matrix, 'sigmoid',[100000, 100000, 100000, 50], 5)
model.start_network()
model.print_result()

[[   0.  153.  510.  706.  966.  581.  455.   70.  160.  372.  157.  567.
   342.]
 [ 153.    0.  422.  664.  997.  598.  507.  197.  311.  479.  310.  581.
   417.]
 [ 510.  422.    0.  289.  744.  390.  437.  491.  645.  880.  618.  374.
   455.]
 [ 706.  664.  289.    0.  491.  265.  410.  664.  804. 1070.  768.  259.
   499.]
 [ 966.  997.  744.  491.    0.  400.  514.  902.  990. 1261.  947.  418.
   635.]
 [ 581.  598.  390.  265.  400.    0.  168.  522.  634.  910.  593.   19.
   284.]
 [ 455.  507.  437.  410.  514.  168.    0.  389.  482.  757.  439.  163.
   124.]
 [  70.  197.  491.  664.  902.  522.  389.    0.  154.  406.  133.  508.
   273.]
 [ 160.  311.  645.  804.  990.  634.  482.  154.    0.  276.   43.  623.
   358.]
 [ 372.  479.  880. 1070. 1261.  910.  757.  406.  276.    0.  318.  898.
   633.]
 [ 157.  310.  618.  768.  947.  593.  439.  133.   43.  318.    0.  582.
   315.]
 [ 567.  581.  374.  259.  418.   19.  163.  508.  623.  898.  582.    0.
   275.]
 [ 3

In [10]:
matrix = np.array(parsing('burma14.xml', 0))
print(matrix)
model = HopfieldModel(matrix, 'sigmoid',[150000, 150000, 150000, 50], 5)
model.start_network()
model.print_result()

[[   0.  153.  510.  706.  966.  581.  455.   70.  160.  372.  157.  567.
   342.  398.]
 [ 153.    0.  422.  664.  997.  598.  507.  197.  311.  479.  310.  581.
   417.  376.]
 [ 510.  422.    0.  289.  744.  390.  437.  491.  645.  880.  618.  374.
   455.  211.]
 [ 706.  664.  289.    0.  491.  265.  410.  664.  804. 1070.  768.  259.
   499.  310.]
 [ 966.  997.  744.  491.    0.  400.  514.  902.  990. 1261.  947.  418.
   635.  636.]
 [ 581.  598.  390.  265.  400.    0.  168.  522.  634.  910.  593.   19.
   284.  239.]
 [ 455.  507.  437.  410.  514.  168.    0.  389.  482.  757.  439.  163.
   124.  232.]
 [  70.  197.  491.  664.  902.  522.  389.    0.  154.  406.  133.  508.
   273.  355.]
 [ 160.  311.  645.  804.  990.  634.  482.  154.    0.  276.   43.  623.
   358.  498.]
 [ 372.  479.  880. 1070. 1261.  910.  757.  406.  276.    0.  318.  898.
   633.  761.]
 [ 157.  310.  618.  768.  947.  593.  439.  133.   43.  318.    0.  582.
   315.  464.]
 [ 567.  581.  374.  

KeyboardInterrupt: 

### Метод ветвей и границ

In [2]:
matrix = parsing('burma14.xml', float('inf'), 8)
BnB_model = BnBMethod()
print(BnB_model.start(np.array(matrix), 1))

(2382.0, [0, 7, 6, 5, 4, 3, 2, 1, 0])


In [3]:
matrix = parsing('burma14.xml', float('inf'), 9)
BnB_model = BnBMethod()
print(BnB_model.start(np.array(matrix), 1))

(2626.0, [0, 8, 7, 6, 5, 4, 3, 2, 1, 0])


In [4]:
matrix = parsing('burma14.xml', float('inf'), 10)
BnB_model = BnBMethod()
print(BnB_model.start(np.array(matrix), 1))

(3114.0, [0, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0])


In [5]:
matrix = parsing('burma14.xml', float('inf'), 11)
BnB_model = BnBMethod()
print(BnB_model.start(np.array(matrix), 1))

(3136.0, [0, 9, 8, 10, 7, 6, 5, 4, 3, 2, 1, 0])


In [2]:
matrix = parsing('burma14.xml', float('inf'), 12)
BnB_model = BnBMethod()
print(BnB_model.start(np.array(matrix), 1))

In [2]:
BnB_model = BnBMethod()
matrix = parsing('burma14.xml', float('inf'))
print(BnB_model.start(np.array(matrix), 1))

KeyboardInterrupt: 

In [6]:
matrix = parsing('burma14.xml', float('inf'))

In [7]:
import pandas as pd
df1 = pd.DataFrame(matrix)
df1.to_excel("output.xlsx")  